# Generated by Django 4.0.5 on 2022-07-12 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userweightheightentry_recorded_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='userweightheightentry',
            name='user_bmi',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
